apiVersion: v2
name: platform-monitoring
description: Observability stack — Grafana, Loki, Promtail, Prometheus
version: 0.10.0
type: application
dependencies:
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 86.1.0
    repository: https://prometheus-community.github.io/helm-charts
