# Promtail values to collect logs from Kubernetes pods and push to Loki
# Chart: grafana/promtail

config:
  logLevel: info
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
