apiVersion: v2
name: platform-external-secrets
description: External secrets management — External Secrets Operator
version: 0.7.0
type: application
dependencies:
  - name: external-secrets
    version: 0.14.3
    repository: https://charts.external-secrets.io
