# Enable/disable individual security tools
falco:
  enabled: true
  fullnameOverride: falco
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

falcosidekick:
  enabled: false

tetragon:
  enabled: true
  fullnameOverride: tetragon
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

trivy-operator:
  enabled: true
  fullnameOverride: trivy-operator
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
