# ServiceAccount configured for Vault authentication

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  labels:
    app.kubernetes.io/component: vault-auth
automountServiceAccountToken: true

---
# Secret containing the ServiceAccount token (used by ExternalSecret ClusterSecretStore)
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-token
  annotations:
    kubernetes.io/description: "Token for Vault authentication via ExternalSecret"
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
