apiVersion: v2
name: platform-argocd
description: GitOps — ArgoCD
version: 0.5.0
type: application
dependencies:
  - name: argo-cd
    version: 7.8.26
    repository: https://argoproj.github.io/argo-helm
