apiVersion: v2
name: platform-argocd
description: GitOps — ArgoCD
version: 1.2.0
type: application
dependencies:
  - name: argo-cd
    version: 9.5.17
    repository: https://argoproj.github.io/argo-helm
