{{- if or .Values.jobCore.enabled .Values.jobApps.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-seeder-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "platform-vault-seeder.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Vault
  vault-root-token: {{ .Values.secrets.vaultRootToken | quote }}

  # OIDC
  oidc-client-id: {{ .Values.secrets.oidcClientId | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}

  # ArgoCD
  argocd-server-secret-key: {{ .Values.secrets.argocdServerSecretKey | quote }}
  homepage-argocd-token: {{ .Values.secrets.homepageArgocdToken | quote }}

  # Grafana
  grafana-password: {{ .Values.secrets.grafanaPassword | quote }}

  # GHCR
  ghcr-pat: {{ .Values.secrets.ghcrPat | quote }}

  # Reactive Resume
  rr-auth-secret: {{ .Values.secrets.rrAuthSecret | quote }}
  rr-db-password: {{ .Values.secrets.rrDbPassword | quote }}
  rr-browserless-token: {{ .Values.secrets.rrBrowserlessToken | quote }}
  rr-database-url: {{ .Values.secrets.rrDatabaseUrl | default "" | quote }}
  rr-printer-endpoint: {{ .Values.secrets.rrPrinterEndpoint | default "" | quote }}
  rr-s3-access-key-id: {{ .Values.secrets.rrS3AccessKeyId | quote }}
  rr-s3-secret-access-key: {{ .Values.secrets.rrS3SecretAccessKey | quote }}
{{- end }}
