# ServiceAccount template — to be customized per-app

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app.kubernetes.io/component: service-account
automountServiceAccountToken: true
