apiVersion: v2
name: platform-vault
description: Secret management — Vault (ESO managed separately)
version: 0.11.2
type: application
dependencies:
  - name: vault
    version: 0.32.0
    repository: https://helm.releases.hashicorp.com
