apiVersion: v2
name: platform-vault
description: Secret management — Vault (ESO managed separately)
version: 0.7.0
type: application
dependencies:
  - name: vault
    version: 0.29.1
    repository: https://helm.releases.hashicorp.com
