vault:
  fullnameOverride: vault
  global:
    enabled: true
    tlsDisable: true
  injector:
    enabled: false
  server:
    image:
      repository: hashicorp/vault
      tag: "1.19.0"
      pullPolicy: IfNotPresent
    ha:
      enabled: false
    dataStorage:
      enabled: true
      size: 5Gi
      storageClass: local-path
    auditStorage:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    readinessProbe:
      enabled: true
      path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
    livenessProbe:
      enabled: true
      path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
      initialDelaySeconds: 60
    ingress:
      enabled: false
    standalone:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable     = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "vault-0"
        }

        service_registration "kubernetes" {}

        disable_mlock = true
  ui:
    enabled: true
    serviceType: ClusterIP
