apiVersion: v2
name: platform-traefik
description: Ingress controller — Traefik with CRDs and dashboard
version: 0.15.0
type: application
dependencies:
  - name: traefik
    version: 41.0.2
    repository: https://traefik.github.io/charts
